sources:
    - name: Mongoose
      handler:
        name: mongoose
        source: mongodb://localhost:27017/test
        config:
            models:
                - name: User
                  path: ./src/models.ts#User

