- output: ./src/generated-sdk/
  sources:
    - name: Cities
      # Docs: https://wirefreethought.github.io/geodb-cities-api-docs/
      source: https://api.apis.guru/v2/specs/mashape.com/geodb/1.0.0/swagger.json
      handler:
        name: typescript-swagger
        config:
          apiKey: f93d3b393dmsh13fea7cb6981b2ep1dba0ajsn654ffeb48c26
    - name: Weather
      source: https://api.apis.guru/v2/specs/weatherbit.io/2.0.0/swagger.json
      handler:
        name: typescript-swagger
  transformations:
    - type: link
      from: PopulatedPlaceSummary.dailyForecast
      to: "[Forecast!]!"
  additionalResolvers:
    - ./src/my-resolvers.ts
