sources:
  - name: Example
    handler:
      grpc:
        endpoint: localhost:50051
        credentialsSsl:
          rootCA: ./certs/ca.crt
          certChain: ./certs/server.crt
          privateKey: ./certs/server.key
        protoFilePath:
          file: io/xtech/service.proto
          load:
            includeDirs:
              - ./proto
        serviceName: Example
        packageName: io.xtech
