sources:
  - name: KLM UTE3
    handler:
      name: json-schema
      config: 
        baseUrl: https://api-ute3.airfranceklm.com/
        schemaHeaders:
          Host: api-ute3.airfranceklm.com
          Accept: application/hal+json;charset=UTF-8;
          Content-Type: application/json
          Authorization: Bearer y8egfms4fjkh87rvk9b7qtgr
          AFKL-TRAVEL-Host: AF
        operationHeaders:
          Accept: application/hal+json;profile=com.afklm.flightoffers.lowest-fare-offers.v3;
          Authorization: Bearer w9wx32bwa63bgcccgc8xd79r
          Content-Type: application/json
          AFKL-TRAVEL-Host: AF
          AFKL-TRAVEL-Country: GR
          Accept-Language: en-GR
          blueweb-identified-bot: BOT
        typeReferences: 
          - reference: "urn:jsonschema:org:joda:time:LocalDate"
            sharedType: graphql-scalars#DateTimeResolver
          - reference: "urn:jsonschema:org:joda:time:LocalDateTime"
            sharedType: graphql-scalars#DateTimeResolver
          - reference: "urn:jsonschema:com:afklm:ofa:util:DateInterval"
            sharedType: graphql#GraphQLString
        operations:
          - type: Query
            field: availableOffers
            path: /travel/offers/v1/available-offers
            method: POST
            requestSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/request/available-offers
            responseSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/response/available-offers
          - type: Query
            field: upsellOffers
            path: /travel/offers/v1/upsell-offers
            method: POST
            requestSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/request/upsell-offers
            responseSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/response/upsell-offers
          - type: Query
            field: lowestFareOffers
            path: /travel/offers/v1/lowest-fare-offers
            method: POST
            requestSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/request/lowest-fare-offers
            responseSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/response/lowest-fare-offers
          - type: Query
            field: tripSummary
            path: /travel/offers/v1/trip-summary
            method: POST
            requestSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/request/trip-summary
            responseSchema: https://api-ute3.airfranceklm.com/travel/offers/v1/jsonschema/response/trip-summary
