sources:
  - name: FHIR
    handler:
      fhir:
        endpoint: http://hapi.fhir.org/baseR4

  - name: Covid
    handler:
      graphql:
        endpoint: https://covid-19.dava.engineer/api/graphql
additionalTypeDefs: |
  extend type Reference {
    resource: ResourceList
  }
  extend type Address {
    case: Case
  }
additionalResolvers:
  - ./resource.resolver.js # Programmatic API
  - type: Address # Declarative API
    field: case
    requiredSelectionSet: |
      {
        country
      }
    targetSource: Covid
    targetMethod: case
    args:
      countryRegion: '{root.country}'

serve:
  exampleQuery: ./example-queries/*.graphql
