sources:
  - name: Geo
    source: postgres://postgres:docker@localhost/postgres
    handler:
      name: postgraphile
    transformations:
      - type: prefix
  - name: Github
    source: https://api.github.com/graphql
    handler:
      name: graphql
      config:
        headers:
          Authorization: bearer ${GH_ACCESS_TOKEN}
    transformations:
      - type: prefix
        includeRootOperations: true
transformations:
  - type: extend
    sdl: |
      extend type Geo_City {
        developers(limit: Int = 10): [Github_User!]!
      }
additionalResolvers:
  - ./src/mesh/additional-resolvers.ts
