sources:
  - name: Geo
    handler:
      name: postgraphile
      source: postgres://postgres:docker@localhost/postgres
    transformations:
      - type: prefix
  - name: Github
    handler:
      name: graphql
      source: https://api.github.com/graphql
      config:
        headers:
          Authorization: bearer ${GH_ACCESS_TOKEN}
    transformations:
      - type: prefix
        includeRootOperations: true
transformations:
  - type: extend
    sdl: |
      extend type Geo_City {
        developers(limit: Int = 10): Github_SearchResultItemConnection!
      }
additionalResolvers:
  - ./src/mesh/additional-resolvers.ts
