sources:
  - name: Github
    source: https://api.github.com/graphql
    handler:
      name: graphql
      config:
        headers:
          Authorization: bearer edbb871d79e845107185ccbaba142fd7e2b9c33f
    transformations:
      - type: prefix
        includeRootOperations: true
        