sources:
  - name: TripPin
    handler:
      odata:
        baseUrl: https://services.odata.org/TripPinRESTierService/(S(qzsyox3345c15qeq305pblvw))/
        batch: multipart
        expandNavProps: true

serve:
  exampleQuery: example-query.graphql
