name: Website Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy Website
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy_website]') || contains(github.event.head_commit.message, 'chore(release)') || contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git Credientials
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          echo "machine github.com login ${{github.actor}} password ${{secrets.GITHUB_TOKEN}}" > ~/.netrc
      - name: Add origin remote and refetch master
        run: |
          git remote rm origin
          git remote add origin "https://github.com/${{github.repository}}"
          git fetch
          git checkout master
          git reset --hard
      - name: Use Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
      # Workaround for the issue https://exerror.com/failed-to-construct-transformer-error-error0308010cdigital-envelope-routinesunsupported/#:~:text=%3A%3Aunsupported%20Error%20%3F-,To%20Solve%20Failed%20to%20construct%20transformer%3A%20Error%3A%20error%3A0308010C,your%20error%20must%20be%20solved.
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-17-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-17-yarn-

      - name: Install Dependencies using Yarn
        run: yarn install && git checkout yarn.lock
      - name: Build
        run: yarn build
      - name: Deploy 🚀
        run: yarn deploy:website
        env:
          GIT_USER: ${{github.actor}}
